(defpackage :gradual-common-lisp
  (:nicknames :gcl)
  (:import-from :common-lisp :nil)
  (:shadow :defun :defparameter)
  (:use :cl :gradual)
  (:export :nil))

(in-package :gradual-common-lisp)

(defmacro defun (name args &body body)
  `(gradual::typed-defun ,name ,args ,@body))

(defmacro defparameter (name &optional value type)
  `(gradual::typed-defparameter ,name ,value ,type))

;; Export all common-lisp package symbols

(eval-when (:compile-toplevel :load-toplevel :execute)
  (do-external-symbols (s :common-lisp)
    (export (find-symbol (symbol-name s)) :gradual-common-lisp)))

#+nil(do-external-symbols (s :common-lisp)
  (when (ignore-errors (symbol-function s))
    (let ((function-type (sb-kernel::type-specifier (sb-kernel::info :function :type s))))
      (if (listp function-type)
	  (format t "~A~%" `(defun-type ,s (fun ,@(rest function-type))))
	  (format t "~A~%" `(defun-type ,s (fun (&rest t) t)))))))

;; common-lisp package types

(DEFUN-TYPE NREVERSE (FUN (SEQUENCE) (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE UNTRACE (FUN * NIL))
(DEFUN-TYPE REVERSE
            (FUN (SEQUENCE)
                 (VALUES
                  (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                  &OPTIONAL)))
(DEFUN-TYPE PEEK-CHAR
            (FUN
             (&OPTIONAL (OR CHARACTER (MEMBER NIL T))
              (OR STREAM (MEMBER NIL T)) T T T)
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE ENSURE-DIRECTORIES-EXIST
            (FUN (T &KEY (VERBOSE T) (MODE T))
                 (VALUES T (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE FORMAT
            (FUN
             ((OR (MEMBER NIL T) STREAM (VECTOR CHARACTER) (VECTOR NIL)
                  BASE-STRING)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING FUNCTION)
              &REST T)
             (VALUES (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING NULL)
                     &OPTIONAL)))
(DEFUN-TYPE CELL-ERROR-NAME (FUN (T) *))
(DEFUN-TYPE MEMBER-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DECF (FUN * NIL))
(DEFUN-TYPE INTEGERP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAKE-INSTANCES-OBSOLETE (FUN (T) *))
(DEFUN-TYPE SYMBOL-NAME (FUN (SYMBOL) (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE REMOVE-METHOD (FUN (T T) *))
(DEFUN-TYPE AND (FUN * NIL))
(DEFUN-TYPE CASE (FUN * NIL))
(DEFUN-TYPE SXHASH (FUN (T) (VALUES (UNSIGNED-BYTE 62) &OPTIONAL)))
(DEFUN-TYPE CIS
            (FUN (REAL)
                 (VALUES
                  (OR (COMPLEX SINGLE-FLOAT) (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE SUBSTITUTE-IF-NOT
            (FUN
             (T (OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE REST (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE IMAGPART (FUN (NUMBER) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE STRING-DOWNCASE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE SUBSTITUTE
            (FUN
             (T T SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE FIND-RESTART
            (FUN
             ((OR (AND SYMBOL (NOT NULL)) RESTART) &OPTIONAL
              (OR CONDITION NULL))
             (VALUES (OR RESTART NULL) &OPTIONAL)))
(DEFUN-TYPE REMOVE
            (FUN
             (T SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE VECTORP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE STRING-RIGHT-TRIM
            (FUN
             (SEQUENCE
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE STABLE-SORT
            (FUN
             (SEQUENCE (OR FUNCTION SYMBOL) &REST T &KEY
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE RPLACA (FUN (CONS T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CAAAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FLOAT-PRECISION (FUN (FLOAT) (VALUES (MOD 54) &OPTIONAL)))
(DEFUN-TYPE FLOAT (FUN (REAL &OPTIONAL FLOAT) (VALUES FLOAT &OPTIONAL)))
(DEFUN-TYPE REDUCE
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))) (INITIAL-VALUE T)
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE PRINC
            (FUN (T &OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE DEPOSIT-FIELD
            (FUN (INTEGER CONS INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE ARRAYP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE USE-VALUE
            (FUN (T &OPTIONAL (OR CONDITION NULL))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PACKAGE-USE-LIST
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE WRITE-STRING
            (FUN
             (STRING &OPTIONAL (OR STREAM (MEMBER NIL T)) &KEY
                     (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901))))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE PACKAGE-USED-BY-LIST
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE PATHNAME-TYPE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (CASE (MEMBER LOCAL COMMON)))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING PATTERN (MEMBER NIL UNSPECIFIC WILD))
              &OPTIONAL)))
(DEFUN-TYPE CDADDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LISP-IMPLEMENTATION-VERSION
            (FUN NIL (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE PAIRLIS (FUN (T T &OPTIONAL T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE MAKE-LIST
            (FUN ((MOD 4611686018427387901) &KEY (INITIAL-ELEMENT T))
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DO-EXTERNAL-SYMBOLS (FUN * NIL))
(DEFUN-TYPE SET (FUN (SYMBOL T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE REPLACE
            (FUN
             (SEQUENCE SEQUENCE &REST T &KEY
              (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE HANDLER-CASE (FUN * NIL))
(DEFUN-TYPE FIND
            (FUN
             (T SEQUENCE &REST T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901)) (FROM-END T)
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE BYTE-SIZE (FUN (CONS) (VALUES (UNSIGNED-BYTE 62) &OPTIONAL)))
(DEFUN-TYPE PACKAGE-NICKNAMES
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE MAKE-SYNONYM-STREAM
            (FUN (SYMBOL) (VALUES SYNONYM-STREAM &OPTIONAL)))
(DEFUN-TYPE BROADCAST-STREAM-STREAMS
            (FUN (BROADCAST-STREAM) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE WHEN (FUN * NIL))
(DEFUN-TYPE PPRINT-FILL
            (FUN ((OR STREAM (MEMBER NIL T)) T &OPTIONAL T T)
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE ROOM
            (FUN (&OPTIONAL (MEMBER T NIL DEFAULT)) (VALUES &OPTIONAL)))
(DEFUN-TYPE SET-DISPATCH-MACRO-CHARACTER
            (FUN
             (CHARACTER CHARACTER (OR FUNCTION SYMBOL) &OPTIONAL
                        (OR READTABLE NULL))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE CAADAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE DELETE-DUPLICATES
            (FUN
             (SEQUENCE &REST T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901)) (FROM-END T)
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE MAPCAN
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE CAADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CHAR-NOT-EQUAL
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE PPRINT-LOGICAL-BLOCK (FUN * NIL))
(DEFUN-TYPE TRUNCATE
            (FUN (REAL &OPTIONAL REAL) (VALUES INTEGER REAL &OPTIONAL)))
(DEFUN-TYPE EQUALP (FUN (T T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE REMF (FUN * NIL))
(DEFUN-TYPE SIMPLE-CONDITION-FORMAT-ARGUMENTS (FUN (T) *))
(DEFUN-TYPE SCALE-FLOAT (FUN (FLOAT INTEGER) (VALUES FLOAT &OPTIONAL)))
(DEFUN-TYPE IF (FUN * NIL))
(DEFUN-TYPE CALL-METHOD (FUN * NIL))
(DEFUN-TYPE WARN (FUN (T &REST T) (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE LIST-ALL-PACKAGES (FUN NIL (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LCM (FUN (&REST INTEGER) (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE ADJUST-ARRAY
            (FUN
             (ARRAY (OR (MOD 4611686018427387901) CONS NULL) &KEY
              (ELEMENT-TYPE (OR CONS SYMBOL INSTANCE)) (INITIAL-ELEMENT T)
              (INITIAL-CONTENTS T) (FILL-POINTER T)
              (DISPLACED-TO (OR ARRAY NULL))
              (DISPLACED-INDEX-OFFSET (MOD 4611686018427387901)))
             (VALUES ARRAY &OPTIONAL)))
(DEFUN-TYPE REMOVE-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE COPY-PPRINT-DISPATCH
            (FUN (&OPTIONAL (OR PPRINT-DISPATCH-TABLE NULL))
                 (VALUES PPRINT-DISPATCH-TABLE &OPTIONAL)))
(DEFUN-TYPE EXPORT
            (FUN
             ((OR CONS SYMBOL) &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE DEFINE-COMPILER-MACRO (FUN * NIL))
(DEFUN-TYPE REMHASH (FUN (T HASH-TABLE) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CHAR/=
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE LIST* (FUN (T &REST T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LOGICAL-PATHNAME-TRANSLATIONS
            (FUN ((OR HOST (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING))
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CAAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE SQRT
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE GET (FUN (SYMBOL T &OPTIONAL T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CHAR-NAME
            (FUN (CHARACTER)
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE ECHO-STREAM-OUTPUT-STREAM
            (FUN (ECHO-STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE CDDADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE SOME
            (FUN ((OR FUNCTION SYMBOL) SEQUENCE &REST SEQUENCE)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE WITH-OPEN-STREAM (FUN * NIL))
(DEFUN-TYPE ARITHMETIC-ERROR-OPERANDS (FUN (T) *))
(DEFUN-TYPE OPEN-STREAM-P (FUN (T) *))
(DEFUN-TYPE MACROEXPAND-1
            (FUN (T &OPTIONAL (OR LEXENV NULL))
                 (VALUES T &OPTIONAL (MEMBER T NIL))))
(DEFUN-TYPE SOFTWARE-VERSION
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE WITH-COMPILATION-UNIT (FUN * NIL))
(DEFUN-TYPE DO-ALL-SYMBOLS (FUN * NIL))
(DEFUN-TYPE PACKAGEP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ENDP (FUN (LIST) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE OR (FUN * NIL))
(DEFUN-TYPE APPEND (FUN * (VALUES T &OPTIONAL)))
(DEFUN-TYPE UPDATE-INSTANCE-FOR-REDEFINED-CLASS (FUN (T T T T &REST T) *))
(DEFUN-TYPE READ-BYTE (FUN (STREAM &OPTIONAL T T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CADDAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE ARRAY-DISPLACEMENT
            (FUN (ARRAY)
                 (VALUES (OR (SIMPLE-ARRAY * (*)) NULL)
                         (OR NULL (MOD 4611686018427387901)) &OPTIONAL)))
(DEFUN-TYPE CHAR-NOT-LESSP
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SYMBOL-VALUE (FUN (SYMBOL) (VALUES T &OPTIONAL)))
(DEFUN-TYPE SEVENTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE COND (FUN * NIL))
(DEFUN-TYPE ISQRT (FUN (UNSIGNED-BYTE) (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE DEFPACKAGE (FUN * NIL))
(DEFUN-TYPE FIND-IF
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE BIT-ANDC1
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE PARSE-INTEGER
            (FUN
             (STRING &KEY (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901)))
                     (RADIX (INTEGER 2 36)) (JUNK-ALLOWED T))
             (VALUES (OR INTEGER NULL) (MOD 4611686018427387901)
                     &OPTIONAL)))
(DEFUN-TYPE LOGIOR (FUN (&REST INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE BIT-NAND
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE LOGXOR (FUN (&REST INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE NAME-CHAR
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES (OR CHARACTER NULL) &OPTIONAL)))
(DEFUN-TYPE SLOT-MISSING (FUN (T T T T &OPTIONAL T) *))
(DEFUN-TYPE APROPOS-LIST
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              T)
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE TENTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FILE-WRITE-DATE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES (OR UNSIGNED-BYTE NULL) &OPTIONAL)))
(DEFUN-TYPE BIT-ORC1
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE SYNONYM-STREAM-SYMBOL
            (FUN (SYNONYM-STREAM) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE WITH-HASH-TABLE-ITERATOR (FUN * NIL))
(DEFUN-TYPE AREF
            (FUN (ARRAY &REST (MOD 4611686018427387901))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE SUBST-IF-NOT
            (FUN
             (T (OR FUNCTION SYMBOL) T &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE MAKE-RANDOM-STATE
            (FUN
             (&OPTIONAL
              (OR (MEMBER NIL T) RANDOM-STATE UNSIGNED-BYTE
                  (SIMPLE-ARRAY (UNSIGNED-BYTE 8) (*))
                  (SIMPLE-ARRAY (UNSIGNED-BYTE 32) (*))))
             (VALUES RANDOM-STATE &OPTIONAL)))
(DEFUN-TYPE ED
            (FUN
             (&OPTIONAL
              (OR SYMBOL CONS (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                  PATHNAME))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE COMPLEMENT (FUN (FUNCTION) (VALUES FUNCTION &OPTIONAL)))
(DEFUN-TYPE ATANH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE SVREF
            (FUN (SIMPLE-VECTOR (MOD 4611686018427387901))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE MAKE-TWO-WAY-STREAM
            (FUN (STREAM STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE MAKUNBOUND (FUN (SYMBOL) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE INTEGER-LENGTH
            (FUN (INTEGER) (VALUES (UNSIGNED-BYTE 62) &OPTIONAL)))
(DEFUN-TYPE CONTINUE
            (FUN (&OPTIONAL (OR CONDITION NULL)) (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE COMPUTE-APPLICABLE-METHODS (FUN (T T) *))
(DEFUN-TYPE PARSE-NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &OPTIONAL
              (OR CONS HOST (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                  (MEMBER UNSPECIFIC NIL))
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))) (JUNK-ALLOWED T))
             (VALUES (OR PATHNAME NULL)
                     (OR NULL (MOD 4611686018427387901)) &OPTIONAL)))
(DEFUN-TYPE LOAD
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  STREAM)
              &KEY (VERBOSE T) (PRINT T) (IF-DOES-NOT-EXIST T)
              (EXTERNAL-FORMAT (OR KEYWORD (CONS KEYWORD T))))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE + (FUN (&REST NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE CDADAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE REQUIRE (FUN (T &OPTIONAL T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE COUNT-IF
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (FUN (T T &REST T) *))
(DEFUN-TYPE FLET (FUN * NIL))
(DEFUN-TYPE FDEFINITION
            (FUN ((OR SYMBOL CONS)) (VALUES FUNCTION &OPTIONAL)))
(DEFUN-TYPE STRING>=
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE POSITION-IF
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE STRING-UPCASE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE RANDOM
            (FUN
             ((OR (SINGLE-FLOAT (0.0)) (DOUBLE-FLOAT (0.0d0)) (INTEGER 1))
              &OPTIONAL RANDOM-STATE)
             (VALUES
              (OR (SINGLE-FLOAT 0.0) (DOUBLE-FLOAT 0.0d0) UNSIGNED-BYTE)
              &OPTIONAL)))
(DEFUN-TYPE ENOUGH-NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE CTYPECASE (FUN * NIL))
(DEFUN-TYPE PATHNAME-HOST
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (CASE (MEMBER LOCAL COMMON)))
             (VALUES (OR HOST NULL) &OPTIONAL)))
(DEFUN-TYPE BOUNDP (FUN (SYMBOL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE RETURN-FROM (FUN * NIL))
(DEFUN-TYPE MAKE-SEQUENCE
            (FUN
             ((OR CONS SYMBOL INSTANCE) (MOD 4611686018427387901) &KEY
              (INITIAL-ELEMENT T))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE UNINTERN
            (FUN
             (SYMBOL &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE NOT (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SYMBOL-PLIST (FUN (SYMBOL) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE IMPORT
            (FUN
             ((OR CONS SYMBOL) &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE < (FUN (REAL &REST REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SUBSETP
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE COMPILE-FILE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY
              (OUTPUT-FILE
               (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                   FILE-STREAM (MEMBER T NIL)))
              (VERBOSE T) (PRINT T)
              (EXTERNAL-FORMAT (OR KEYWORD (CONS KEYWORD T)))
              (TRACE-FILE T) (BLOCK-COMPILE T) (EMIT-CFASL T))
             (VALUES (OR PATHNAME NULL) (MEMBER T NIL) (MEMBER T NIL)
                     &OPTIONAL)))
(DEFUN-TYPE ARRAY-RANK (FUN (ARRAY) (VALUES (MOD 65529) &OPTIONAL)))
(DEFUN-TYPE LOWER-CASE-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE NSTRING-DOWNCASE
            (FUN
             (STRING &KEY (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901))))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE FBOUNDP
            (FUN ((OR SYMBOL CONS)) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE * (FUN (&REST NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE RPLACD (FUN (CONS T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE NUNION
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LOAD-TIME-VALUE (FUN * NIL))
(DEFUN-TYPE RASSOC-IF
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DIRECTORY-NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE DESCRIBE
            (FUN (T &OPTIONAL (OR STREAM (MEMBER T NIL)))
                 (VALUES &OPTIONAL)))
(DEFUN-TYPE INITIALIZE-INSTANCE (FUN (T &REST T &KEY &ALLOW-OTHER-KEYS) *))
(DEFUN-TYPE STRING-CAPITALIZE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE PROGN (FUN * NIL))
(DEFUN-TYPE FILL-POINTER
            (FUN ((AND VECTOR (NOT SIMPLE-ARRAY)))
                 (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE SUBST
            (FUN
             (T T T &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE FUNCTION-LAMBDA-EXPRESSION
            (FUN (FUNCTION) (VALUES T (MEMBER T NIL) T &OPTIONAL)))
(DEFUN-TYPE SIGNAL (FUN (T &REST T) (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE ACOS
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE DELETE-PACKAGE (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE BUTLAST
            (FUN (LIST &OPTIONAL UNSIGNED-BYTE) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LENGTH
            (FUN (SEQUENCE) (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE NUMBERP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE FLOATP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SET-EXCLUSIVE-OR
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DEFGENERIC (FUN * NIL))
(DEFUN-TYPE ETYPECASE (FUN * NIL))
(DEFUN-TYPE MOD (FUN (REAL REAL) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE ERROR (FUN (T &REST T) NIL))
(DEFUN-TYPE MUFFLE-WARNING (FUN (&OPTIONAL (OR CONDITION NULL)) NIL))
(DEFUN-TYPE BIT-EQV
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE GET-OUTPUT-STREAM-STRING
            (FUN (STREAM) (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE LDIFF (FUN (LIST T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LISTP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE INTERSECTION
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DOCUMENTATION (FUN (T T) *))
(DEFUN-TYPE MAKE-STRING
            (FUN
             ((MOD 4611686018427387901) &KEY
              (ELEMENT-TYPE (OR CONS SYMBOL INSTANCE))
              (INITIAL-ELEMENT CHARACTER))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE LIST-LENGTH
            (FUN (LIST)
                 (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE BLOCK (FUN * NIL))
(DEFUN-TYPE STRING=
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE COMPILED-FUNCTION-P
            (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CADADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LOGBITP
            (FUN (UNSIGNED-BYTE INTEGER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE NO-NEXT-METHOD (FUN (&REST T) T))
(DEFUN-TYPE DOTIMES (FUN * NIL))
(DEFUN-TYPE LDB (FUN (CONS INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE UPGRADED-ARRAY-ELEMENT-TYPE
            (FUN ((OR CONS SYMBOL INSTANCE) &OPTIONAL (OR LEXENV NULL))
                 (VALUES (OR CONS SYMBOL INSTANCE) &OPTIONAL)))
(DEFUN-TYPE APROPOS
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              T)
             (VALUES &OPTIONAL)))
(DEFUN-TYPE MULTIPLE-VALUE-LIST (FUN * NIL))
(DEFUN-TYPE SINH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE READTABLE-CASE
            (FUN (T)
                 (VALUES (MEMBER INVERT PRESERVE DOWNCASE UPCASE)
                         &OPTIONAL)))
(DEFUN-TYPE MAPL
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE HASH-TABLE-TEST (FUN (HASH-TABLE) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE SET-SYNTAX-FROM-CHAR
            (FUN
             (CHARACTER CHARACTER &OPTIONAL READTABLE (OR READTABLE NULL))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE FUNCALL (FUN ((OR FUNCTION SYMBOL) &REST T) *))
(DEFUN-TYPE MERGE
            (FUN
             ((OR CONS SYMBOL INSTANCE) SEQUENCE SEQUENCE
              (OR FUNCTION SYMBOL) &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE DELETE-FILE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE MEMBER
            (FUN
             (T LIST &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE FIND-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE POP (FUN * NIL))
(DEFUN-TYPE ARRAY-HAS-FILL-POINTER-P
            (FUN (ARRAY) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE FILE-NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE NRECONC (FUN (LIST T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE NULL (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE GET-DECODED-TIME
            (FUN NIL
                 (VALUES (MOD 60) (MOD 60) (MOD 24) (INTEGER 1 31)
                         (INTEGER 1 12) UNSIGNED-BYTE (MOD 7)
                         (MEMBER T NIL) (RATIONAL -24 24) &OPTIONAL)))
(DEFUN-TYPE GET-UNIVERSAL-TIME (FUN NIL (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE RATIONALIZE (FUN (REAL) (VALUES RATIONAL &OPTIONAL)))
(DEFUN-TYPE COMPILE
            (FUN ((OR SYMBOL CONS) &OPTIONAL (OR CONS FUNCTION NULL))
                 (VALUES (OR FUNCTION SYMBOL CONS) (MEMBER T NIL)
                         (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE GENTEMP
            (FUN
             (&OPTIONAL STRING
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE FILL
            (FUN
             (SEQUENCE T &REST T &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE CDDAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CDAADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LOGANDC2 (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE CADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE STREAM-ERROR-STREAM (FUN (T) *))
(DEFUN-TYPE NSET-EXCLUSIVE-OR
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CHAR-EQUAL
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SIMPLE-BIT-VECTOR-P
            (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE APPLY (FUN ((OR FUNCTION SYMBOL) T &REST T) *))
(DEFUN-TYPE RESTART-CASE (FUN * NIL))
(DEFUN-TYPE CADDDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FILE-POSITION
            (FUN (STREAM &OPTIONAL (OR UNSIGNED-BYTE (MEMBER START END)))
                 (VALUES (OR UNSIGNED-BYTE (MEMBER T NIL)) &OPTIONAL)))
(DEFUN-TYPE EQ (FUN (T T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE DEFCLASS (FUN * NIL))
(DEFUN-TYPE NTHCDR (FUN (UNSIGNED-BYTE LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FILE-ERROR-PATHNAME (FUN (T) *))
(DEFUN-TYPE CODE-CHAR (FUN ((MOD 1114112)) (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE ACOSH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE =
            (FUN (NUMBER &REST NUMBER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MIN (FUN (REAL &REST REAL) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE READ-DELIMITED-LIST
            (FUN (CHARACTER &OPTIONAL (OR STREAM (MEMBER NIL T)) T)
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CHAR>
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE BIT
            (FUN ((ARRAY BIT) &REST (MOD 4611686018427387901))
                 (VALUES BIT &OPTIONAL)))
(DEFUN-TYPE ARRAY-ELEMENT-TYPE
            (FUN (ARRAY) (VALUES (OR CONS SYMBOL INSTANCE) &OPTIONAL)))
(DEFUN-TYPE OPEN
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (DIRECTION (MEMBER INPUT OUTPUT IO PROBE))
              (ELEMENT-TYPE (OR CONS SYMBOL INSTANCE))
              (IF-EXISTS
               (MEMBER ERROR NEW-VERSION RENAME RENAME-AND-DELETE
                       OVERWRITE APPEND SUPERSEDE NIL))
              (IF-DOES-NOT-EXIST (MEMBER ERROR CREATE NIL))
              (EXTERNAL-FORMAT (OR KEYWORD (CONS KEYWORD T))))
             (VALUES (OR STREAM NULL) &OPTIONAL)))
(DEFUN-TYPE UPGRADED-COMPLEX-PART-TYPE
            (FUN ((OR CONS SYMBOL INSTANCE) &OPTIONAL (OR LEXENV NULL))
                 (VALUES (OR CONS SYMBOL INSTANCE) &OPTIONAL)))
(DEFUN-TYPE PPRINT-NEWLINE
            (FUN
             ((MEMBER LINEAR FILL MISER MANDATORY) &OPTIONAL
              (OR STREAM (MEMBER NIL T)))
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE GO (FUN * NIL))
(DEFUN-TYPE PATHNAME-MATCH-P
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE WITH-OUTPUT-TO-STRING (FUN * NIL))
(DEFUN-TYPE STRING-NOT-GREATERP
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE SHADOW
            (FUN
             ((OR CHARACTER (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                  CONS SYMBOL)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE EQL (FUN (T T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAKE-INSTANCE (FUN (T &REST T &KEY &ALLOW-OTHER-KEYS) *))
(DEFUN-TYPE LET* (FUN * NIL))
(DEFUN-TYPE SBIT
            (FUN ((SIMPLE-ARRAY BIT) &REST (MOD 4611686018427387901))
                 (VALUES BIT &OPTIONAL)))
(DEFUN-TYPE DESCRIBE-OBJECT (FUN (T T) *))
(DEFUN-TYPE ROTATEF (FUN * NIL))
(DEFUN-TYPE WITH-SLOTS (FUN * NIL))
(DEFUN-TYPE ABORT (FUN (&OPTIONAL (OR CONDITION NULL)) NIL))
(DEFUN-TYPE CHAR
            (FUN (STRING (MOD 4611686018427387901))
                 (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE TAGBODY (FUN * NIL))
(DEFUN-TYPE MAPC
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE NOTANY
            (FUN ((OR FUNCTION SYMBOL) SEQUENCE &REST SEQUENCE)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CHANGE-CLASS (FUN (T T &REST T &KEY &ALLOW-OTHER-KEYS) *))
(DEFUN-TYPE PPRINT-EXIT-IF-LIST-EXHAUSTED (FUN * NIL))
(DEFUN-TYPE TYPE-ERROR-DATUM (FUN (T) *))
(DEFUN-TYPE NTH (FUN (UNSIGNED-BYTE LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LISP-IMPLEMENTATION-TYPE
            (FUN NIL (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE NSUBLIS
            (FUN
             (LIST T &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE TERPRI
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PACKAGE-NAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE TWO-WAY-STREAM-INPUT-STREAM
            (FUN (TWO-WAY-STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE REALP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SIMPLE-VECTOR-P (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SUBST-IF
            (FUN
             (T (OR FUNCTION SYMBOL) T &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE BIT-ANDC2
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE WITH-INPUT-FROM-STRING (FUN * NIL))
(DEFUN-TYPE SIMPLE-CONDITION-FORMAT-CONTROL (FUN (T) *))
(DEFUN-TYPE LOGEQV (FUN (&REST INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE CAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE GET-INTERNAL-REAL-TIME
            (FUN NIL (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE DO (FUN * NIL))
(DEFUN-TYPE PROVIDE (FUN (T) (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE LET (FUN * NIL))
(DEFUN-TYPE SIXTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE RENAME-FILE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME))
             (VALUES PATHNAME PATHNAME PATHNAME &OPTIONAL)))
(DEFUN-TYPE MAKE-STRING-OUTPUT-STREAM
            (FUN (&KEY (ELEMENT-TYPE (OR CONS SYMBOL INSTANCE)))
                 (VALUES STRING-OUTPUT-STREAM &OPTIONAL)))
(DEFUN-TYPE NSUBSTITUTE
            (FUN
             (T T SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE STREAMP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAKE-CONDITION
            (FUN ((OR CONS SYMBOL INSTANCE) &REST T)
                 (VALUES CONDITION &OPTIONAL)))
(DEFUN-TYPE DECODE-FLOAT
            (FUN (FLOAT)
                 (VALUES FLOAT (INTEGER -1074 1024) FLOAT &OPTIONAL)))
(DEFUN-TYPE LOGNOR (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE TYPECASE (FUN * NIL))
(DEFUN-TYPE FILE-AUTHOR
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE YES-OR-NO-P
            (FUN (&OPTIONAL STRING &REST T)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE VECTOR (FUN * (VALUES SIMPLE-VECTOR &OPTIONAL)))
(DEFUN-TYPE GET-PROPERTIES (FUN (LIST LIST) (VALUES T T LIST &OPTIONAL)))
(DEFUN-TYPE NSUBST
            (FUN
             (T T T &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE STREAM-EXTERNAL-FORMAT (FUN (T) *))
(DEFUN-TYPE SOFTWARE-TYPE
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE WRITE
            (FUN
             (T &KEY (STREAM (OR STREAM (MEMBER NIL T))) (ESCAPE T)
              (RADIX T) (BASE (INTEGER 2 36)) (CIRCLE T) (PRETTY T)
              (LEVEL (OR UNSIGNED-BYTE NULL)) (READABLY T)
              (LENGTH (OR UNSIGNED-BYTE NULL)) (CASE T) (ARRAY T)
              (GENSYM T) (LINES (OR UNSIGNED-BYTE NULL))
              (RIGHT-MARGIN (OR UNSIGNED-BYTE NULL))
              (MISER-WIDTH (OR UNSIGNED-BYTE NULL)) (PPRINT-DISPATCH T))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE TRANSLATE-PATHNAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY)
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE STRING-LEFT-TRIM
            (FUN
             (SEQUENCE
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE REMOVE-DUPLICATES
            (FUN
             (SEQUENCE &REST T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901)) (FROM-END T)
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE TAN
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE INTERN
            (FUN
             (STRING &OPTIONAL
                     (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                         SYMBOL CHARACTER PACKAGE))
             (VALUES SYMBOL (MEMBER INTERNAL EXTERNAL INHERITED NIL)
                     &OPTIONAL)))
(DEFUN-TYPE STRINGP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE READ-PRESERVING-WHITESPACE
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)) T T T)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE OUTPUT-STREAM-P (FUN (T) *))
(DEFUN-TYPE PSETQ (FUN * NIL))
(DEFUN-TYPE PPRINT-POP (FUN * NIL))
(DEFUN-TYPE MAKE-HASH-TABLE
            (FUN
             (&KEY (TEST (OR FUNCTION SYMBOL)) (SIZE UNSIGNED-BYTE)
              (REHASH-SIZE
               (OR (INTEGER 1) (SINGLE-FLOAT (1.0))
                   (DOUBLE-FLOAT (1.0d0))))
              (REHASH-THRESHOLD
               (OR (SINGLE-FLOAT 0.0 1.0) (DOUBLE-FLOAT 0.0d0 1.0d0)
                   (RATIONAL 0 1)))
              (HASH-FUNCTION (OR FUNCTION SYMBOL))
              (WEAKNESS (MEMBER NIL KEY VALUE KEY-AND-VALUE KEY-OR-VALUE))
              (SYNCHRONIZED T))
             (VALUES HASH-TABLE &OPTIONAL)))
(DEFUN-TYPE COPY-TREE (FUN (T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CHAR=
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CDAAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE SYMBOLP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ASSERT (FUN * NIL))
(DEFUN-TYPE CHAR-NOT-GREATERP
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE WITH-ACCESSORS (FUN * NIL))
(DEFUN-TYPE DIGIT-CHAR-P
            (FUN (CHARACTER &OPTIONAL (INTEGER 2 36))
                 (VALUES (OR (MOD 36) NULL) &OPTIONAL)))
(DEFUN-TYPE UNEXPORT
            (FUN
             ((OR CONS SYMBOL) &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE MAKE-DISPATCH-MACRO-CHARACTER
            (FUN (CHARACTER &OPTIONAL T READTABLE)
                 (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE STANDARD-CHAR-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE READTABLEP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE HANDLER-BIND (FUN * NIL))
(DEFUN-TYPE ASH (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE PRINT-NOT-READABLE-OBJECT (FUN (T) *))
(DEFUN-TYPE DO* (FUN * NIL))
(DEFUN-TYPE CDAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE THE (FUN * NIL))
(DEFUN-TYPE COMPLEXP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SYMBOL-MACROLET (FUN * NIL))
(DEFUN-TYPE GETF (FUN (LIST T &OPTIONAL T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE LOGANDC1 (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE >= (FUN (REAL &REST REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE COERCE
            (FUN (T (OR CONS SYMBOL INSTANCE)) (VALUES T &OPTIONAL)))
(DEFUN-TYPE PRINT-UNREADABLE-OBJECT (FUN * NIL))
(DEFUN-TYPE BYTE-POSITION
            (FUN (CONS) (VALUES (UNSIGNED-BYTE 62) &OPTIONAL)))
(DEFUN-TYPE DEFINE-SETF-EXPANDER (FUN * NIL))
(DEFUN-TYPE ACONS (FUN (T T T) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE DO-SYMBOLS (FUN * NIL))
(DEFUN-TYPE FIND-PACKAGE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (OR PACKAGE NULL) &OPTIONAL)))
(DEFUN-TYPE 1- (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE WRITE-BYTE (FUN (INTEGER STREAM) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE COMPLEX (FUN (REAL &OPTIONAL REAL) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE UNBOUND-SLOT-INSTANCE (FUN (T) *))
(DEFUN-TYPE ARRAY-DIMENSIONS (FUN (ARRAY) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE FILE-STRING-LENGTH (FUN (T T) *))
(DEFUN-TYPE STRING-NOT-LESSP
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE CDDDAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE VALUES-LIST (FUN (LIST) *))
(DEFUN-TYPE STRING<=
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE ELT
            (FUN (SEQUENCE (MOD 4611686018427387901))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE WITH-OPEN-FILE (FUN * NIL))
(DEFUN-TYPE MAPCON
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE ARRAY-TOTAL-SIZE
            (FUN (ARRAY) (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE CLOSE
            (FUN (STREAM &KEY (ABORT T)) (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE EVERY
            (FUN ((OR FUNCTION SYMBOL) SEQUENCE &REST SEQUENCE)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SORT
            (FUN
             (SEQUENCE (OR FUNCTION SYMBOL) &REST T &KEY
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE EVENP (FUN (INTEGER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE STRING-NOT-EQUAL
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE MAP-INTO
            (FUN (SEQUENCE (OR FUNCTION SYMBOL) &REST SEQUENCE)
                 (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE ARRAY-IN-BOUNDS-P
            (FUN (ARRAY &REST INTEGER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ATOM (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE TYPE-OF (FUN (T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE TANH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE SHADOWING-IMPORT
            (FUN
             ((OR CONS SYMBOL) &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE PROCLAIM (FUN (LIST) (VALUES &OPTIONAL)))
(DEFUN-TYPE CERROR
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING FUNCTION) T
              &REST T)
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE MACHINE-VERSION
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE PATHNAME-DIRECTORY
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (CASE (MEMBER LOCAL COMMON)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CAADDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CLASS-NAME (FUN (&REST T) T))
(DEFUN-TYPE CHAR-UPCASE (FUN (CHARACTER) (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE WRITE-TO-STRING
            (FUN
             (T &KEY (ESCAPE T) (RADIX T) (BASE (INTEGER 2 36))
              (READABLY T) (CIRCLE T) (PRETTY T)
              (LEVEL (OR UNSIGNED-BYTE NULL))
              (LENGTH (OR UNSIGNED-BYTE NULL)) (CASE T) (ARRAY T)
              (GENSYM T) (LINES (OR UNSIGNED-BYTE NULL))
              (RIGHT-MARGIN (OR UNSIGNED-BYTE NULL))
              (MISER-WIDTH (OR UNSIGNED-BYTE NULL)) (PPRINT-DISPATCH T))
             (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE POSITION-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE ALPHA-CHAR-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CATCH (FUN * NIL))
(DEFUN-TYPE BIT-XOR
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE EXPT (FUN (NUMBER NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE > (FUN (REAL &REST REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SLOT-MAKUNBOUND (FUN (T T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE REINITIALIZE-INSTANCE
            (FUN (T &REST T &KEY &ALLOW-OTHER-KEYS) *))
(DEFUN-TYPE STRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE STRING-TRIM
            (FUN
             (SEQUENCE
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE PRINT-OBJECT (FUN (T T) *))
(DEFUN-TYPE HASH-TABLE-COUNT
            (FUN (HASH-TABLE)
                 (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE PACKAGE-ERROR-PACKAGE (FUN (T) *))
(DEFUN-TYPE TYPE-ERROR-EXPECTED-TYPE (FUN (T) *))
(DEFUN-TYPE POSITION
            (FUN
             (T SEQUENCE &REST T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901)) (FROM-END T)
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE CADAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE MAKE-ARRAY
            (FUN
             ((OR (MOD 4611686018427387901) CONS NULL) &KEY
              (ELEMENT-TYPE (OR CONS SYMBOL INSTANCE)) (INITIAL-ELEMENT T)
              (INITIAL-CONTENTS T) (ADJUSTABLE T) (FILL-POINTER T)
              (DISPLACED-TO (OR ARRAY NULL))
              (DISPLACED-INDEX-OFFSET (MOD 4611686018427387901)))
             (VALUES ARRAY &OPTIONAL)))
(DEFUN-TYPE SET-DIFFERENCE
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LOGCOUNT (FUN (INTEGER) (VALUES (UNSIGNED-BYTE 62) &OPTIONAL)))
(DEFUN-TYPE WITH-PACKAGE-ITERATOR (FUN * NIL))
(DEFUN-TYPE NSTRING-CAPITALIZE
            (FUN
             (STRING &KEY (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901))))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE ASINH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE FUNCTION-KEYWORDS (FUN (T) *))
(DEFUN-TYPE PRIN1
            (FUN (T &OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE LOGORC1 (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE PROGV (FUN * NIL))
(DEFUN-TYPE RESTART-BIND (FUN * NIL))
(DEFUN-TYPE DEFUN (FUN * NIL))
(DEFUN-TYPE BIT-AND
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE TRACE (FUN * NIL))
(DEFUN-TYPE 1+ (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE CHAR<=
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE THROW (FUN * NIL))
(DEFUN-TYPE RATIONALP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE VALUES (FUN (&REST T) T))
(DEFUN-TYPE LOG
            (FUN (NUMBER &OPTIONAL REAL)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE GET-INTERNAL-RUN-TIME
            (FUN NIL (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE ECHO-STREAM-INPUT-STREAM
            (FUN (ECHO-STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE PPRINT-LINEAR
            (FUN ((OR STREAM (MEMBER NIL T)) T &OPTIONAL T T)
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE READ-CHAR
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)) T T T)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE WRITE-CHAR
            (FUN (CHARACTER &OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE REALPART (FUN (NUMBER) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE FINISH-OUTPUT
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE NCONC (FUN * (VALUES T &OPTIONAL)))
(DEFUN-TYPE FRESH-LINE
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE RENAME-PACKAGE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              &OPTIONAL LIST)
             (VALUES PACKAGE &OPTIONAL)))
(DEFUN-TYPE CLEAR-INPUT
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE TRUENAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE BIT-IOR
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE REMPROP (FUN (SYMBOL T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE USER-HOMEDIR-PATHNAME
            (FUN (&OPTIONAL T) (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE USE-PACKAGE
            (FUN
             ((OR CONS (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE LONG-SITE-NAME
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE PHASE (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE UNION
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LAST (FUN (LIST &OPTIONAL UNSIGNED-BYTE) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CONCATENATED-STREAM-STREAMS
            (FUN (CONCATENATED-STREAM) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE HASH-TABLE-P (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAPLIST
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE MACRO-FUNCTION
            (FUN (SYMBOL &OPTIONAL (OR LEXENV NULL))
                 (VALUES (OR FUNCTION NULL) &OPTIONAL)))
(DEFUN-TYPE COS
            (FUN (NUMBER)
                 (VALUES
                  (OR (SINGLE-FLOAT -1.0 1.0) (DOUBLE-FLOAT -1.0d0 1.0d0)
                      (COMPLEX SINGLE-FLOAT) (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE NSUBSTITUTE-IF
            (FUN
             (T (OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE HASH-TABLE-REHASH-THRESHOLD
            (FUN (HASH-TABLE) (VALUES (SINGLE-FLOAT (0.0) 1.0) &OPTIONAL)))
(DEFUN-TYPE MAKE-BROADCAST-STREAM
            (FUN (&REST STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE COUNT
            (FUN
             (T SEQUENCE &REST T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901)) (FROM-END T)
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE COPY-STRUCTURE
            (FUN (STRUCTURE-OBJECT) (VALUES STRUCTURE-OBJECT &OPTIONAL)))
(DEFUN-TYPE TREE-EQUAL
            (FUN
             (T T &KEY (TEST (OR FUNCTION SYMBOL))
              (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE LDB-TEST
            (FUN (CONS INTEGER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MACROLET (FUN * NIL))
(DEFUN-TYPE MAKE-SYMBOL (FUN (STRING) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE VECTOR-POP
            (FUN ((AND VECTOR (NOT SIMPLE-ARRAY))) (VALUES T &OPTIONAL)))
(DEFUN-TYPE TAILP (FUN (T LIST) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE LOGNAND (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE MISMATCH
            (FUN
             (SEQUENCE SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE NO-APPLICABLE-METHOD (FUN (&REST T) T))
(DEFUN-TYPE BREAK
            (FUN
             (&OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING FUNCTION)
              &REST T)
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PROG1 (FUN * NIL))
(DEFUN-TYPE FIND-CLASS (FUN (T &OPTIONAL T T) *))
(DEFUN-TYPE NSUBST-IF
            (FUN
             (T (OR FUNCTION SYMBOL) T &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE GENSYM
            (FUN
             (&OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                  UNSIGNED-BYTE))
             (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE MERGE-PATHNAMES
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              (OR INTEGER (MEMBER NIL NEWEST WILD UNSPECIFIC)))
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE ABS (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE SETF (FUN * NIL))
(DEFUN-TYPE ADD-METHOD (FUN (T T) *))
(DEFUN-TYPE EXP
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE SCHAR
            (FUN (SIMPLE-STRING (MOD 4611686018427387901))
                 (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE ENCODE-UNIVERSAL-TIME
            (FUN
             ((MOD 60) (MOD 60) (MOD 24) (INTEGER 1 31) (INTEGER 1 12)
              UNSIGNED-BYTE &OPTIONAL (OR NULL (RATIONAL -24 24)))
             (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE SUBTYPEP
            (FUN
             ((OR CONS SYMBOL INSTANCE) (OR CONS SYMBOL INSTANCE)
              &OPTIONAL (OR LEXENV NULL))
             (VALUES (MEMBER T NIL) (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CHAR<
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE LOGNOT (FUN (INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE ROUND
            (FUN (REAL &OPTIONAL REAL) (VALUES INTEGER REAL &OPTIONAL)))
(DEFUN-TYPE DEFSTRUCT (FUN * NIL))
(DEFUN-TYPE CHECK-TYPE (FUN * NIL))
(DEFUN-TYPE READ-FROM-STRING
            (FUN
             (STRING &OPTIONAL T T &KEY (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901)))
                     (PRESERVE-WHITESPACE T))
             (VALUES T (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE DEFMACRO (FUN * NIL))
(DEFUN-TYPE RANDOM-STATE-P (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE BOOLE
            (FUN ((UNSIGNED-BYTE 4) INTEGER INTEGER)
                 (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE CHAR-DOWNCASE (FUN (CHARACTER) (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE SLOT-BOUNDP (FUN (T T) *))
(DEFUN-TYPE DOLIST (FUN * NIL))
(DEFUN-TYPE PRINC-TO-STRING (FUN (T) (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE SIN
            (FUN (NUMBER)
                 (VALUES
                  (OR (SINGLE-FLOAT -1.0 1.0) (DOUBLE-FLOAT -1.0d0 1.0d0)
                      (COMPLEX SINGLE-FLOAT) (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE SPECIAL-OPERATOR-P (FUN (SYMBOL) (VALUES T &OPTIONAL)))
(DEFUN-TYPE MULTIPLE-VALUE-PROG1 (FUN * NIL))
(DEFUN-TYPE STEP (FUN * NIL))
(DEFUN-TYPE UNLESS (FUN * NIL))
(DEFUN-TYPE DPB (FUN (INTEGER CONS INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE NSET-DIFFERENCE
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE LABELS (FUN * NIL))
(DEFUN-TYPE KEYWORDP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CONJUGATE (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE COMPUTE-RESTARTS
            (FUN (&OPTIONAL (OR CONDITION NULL)) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE - (FUN (NUMBER &REST NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE CHAR>=
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CCASE (FUN * NIL))
(DEFUN-TYPE ADJUSTABLE-ARRAY-P
            (FUN (ARRAY) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE PATHNAMEP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE DEFTYPE (FUN * NIL))
(DEFUN-TYPE MAKE-STRING-INPUT-STREAM
            (FUN
             (STRING &OPTIONAL (MOD 4611686018427387901)
                     (OR NULL (MOD 4611686018427387901)))
             (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE MINUSP (FUN (REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE DELETE-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE SUBSEQ
            (FUN
             (SEQUENCE (MOD 4611686018427387901) &OPTIONAL
              (OR NULL (MOD 4611686018427387901)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE MEMBER-IF
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE ASSOC
            (FUN
             (T LIST &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE MULTIPLE-VALUE-SETQ (FUN * NIL))
(DEFUN-TYPE BIT-NOR
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE UPPER-CASE-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ECASE (FUN * NIL))
(DEFUN-TYPE READ-LINE
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)) T T T)
                 (VALUES T (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE EVAL-WHEN (FUN * NIL))
(DEFUN-TYPE READ-CHAR-NO-HANG
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)) T T T)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE SLOT-VALUE (FUN (T SYMBOL) (VALUES T &OPTIONAL)))
(DEFUN-TYPE INVOKE-RESTART-INTERACTIVELY
            (FUN ((OR (AND SYMBOL (NOT NULL)) RESTART)) *))
(DEFUN-TYPE STRING-GREATERP
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE ALLOCATE-INSTANCE (FUN (T &REST T) *))
(DEFUN-TYPE PATHNAME-VERSION
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES (OR INTEGER (MEMBER NIL NEWEST WILD UNSPECIFIC))
                     &OPTIONAL)))
(DEFUN-TYPE RATIONAL (FUN (REAL) (VALUES RATIONAL &OPTIONAL)))
(DEFUN-TYPE WILD-PATHNAME-P
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &OPTIONAL
              (MEMBER NIL HOST DEVICE DIRECTORY NAME TYPE VERSION))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE HOST-NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE DENOMINATOR (FUN (RATIONAL) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE MAKE-CONCATENATED-STREAM
            (FUN (&REST STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE LOOP (FUN * NIL))
(DEFUN-TYPE EIGHTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FLOAT-DIGITS (FUN (FLOAT) (VALUES (MOD 54) &OPTIONAL)))
(DEFUN-TYPE COMPILER-MACRO-FUNCTION
            (FUN (T &OPTIONAL (OR LEXENV NULL))
                 (VALUES (OR FUNCTION NULL) &OPTIONAL)))
(DEFUN-TYPE CDADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FLOAT-RADIX (FUN (FLOAT) (VALUES (INTEGER 2 2) &OPTIONAL)))
(DEFUN-TYPE CDAAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CHAR-INT (FUN (CHARACTER) (VALUES (MOD 1114112) &OPTIONAL)))
(DEFUN-TYPE FMAKUNBOUND
            (FUN ((OR SYMBOL CONS)) (VALUES (OR SYMBOL CONS) &OPTIONAL)))
(DEFUN-TYPE FORMATTER (FUN * NIL))
(DEFUN-TYPE DECODE-UNIVERSAL-TIME
            (FUN (UNSIGNED-BYTE &OPTIONAL (OR NULL (RATIONAL -24 24)))
                 (VALUES (MOD 60) (MOD 60) (MOD 24) (INTEGER 1 31)
                         (INTEGER 1 12) UNSIGNED-BYTE (MOD 7)
                         (MEMBER T NIL) (RATIONAL -24 24) &OPTIONAL)))
(DEFUN-TYPE SLEEP
            (FUN
             ((OR (SINGLE-FLOAT 0.0) (DOUBLE-FLOAT 0.0d0) (RATIONAL 0)))
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE REMOVE-IF
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE IGNORE-ERRORS (FUN * NIL))
(DEFUN-TYPE GRAPHIC-CHAR-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SET-PPRINT-DISPATCH
            (FUN
             ((OR CONS SYMBOL INSTANCE) (OR FUNCTION SYMBOL) &OPTIONAL
              REAL PPRINT-DISPATCH-TABLE)
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PPRINT-DISPATCH
            (FUN (T &OPTIONAL (OR PPRINT-DISPATCH-TABLE NULL))
                 (VALUES (OR FUNCTION SYMBOL) (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE PPRINT-INDENT
            (FUN
             ((MEMBER BLOCK CURRENT) REAL &OPTIONAL
              (OR STREAM (MEMBER NIL T)))
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE THIRD (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE PRIN1-TO-STRING (FUN (T) (VALUES SIMPLE-STRING &OPTIONAL)))
(DEFUN-TYPE MACHINE-INSTANCE
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE GET-MACRO-CHARACTER
            (FUN (CHARACTER &OPTIONAL (OR READTABLE NULL))
                 (VALUES (OR FUNCTION SYMBOL) (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE LIST (FUN * (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE ADJOIN
            (FUN
             (T LIST &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE TIME (FUN * NIL))
(DEFUN-TYPE PRINT
            (FUN (T &OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE LAMBDA (FUN * NIL))
(DEFUN-TYPE DESTRUCTURING-BIND (FUN * NIL))
(DEFUN-TYPE ASSOC-IF
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE SET-MACRO-CHARACTER
            (FUN
             (CHARACTER (OR FUNCTION SYMBOL) &OPTIONAL T
                        (OR READTABLE NULL))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE STRING>
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE MAPHASH
            (FUN ((OR FUNCTION SYMBOL) HASH-TABLE)
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE SYMBOL-FUNCTION (FUN (SYMBOL) (VALUES FUNCTION &OPTIONAL)))
(DEFUN-TYPE FIND-METHOD (FUN (T T T &OPTIONAL T) *))
(DEFUN-TYPE ODDP (FUN (INTEGER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ASIN
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE FORCE-OUTPUT
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE SHIFTF (FUN * NIL))
(DEFUN-TYPE NSTRING-UPCASE
            (FUN
             (STRING &KEY (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901))))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE SEARCH
            (FUN
             (SEQUENCE SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE LOOP-FINISH (FUN * NIL))
(DEFUN-TYPE CLASS-OF (FUN (T) *))
(DEFUN-TYPE DRIBBLE
            (FUN
             (&OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME)
              &KEY (IF-EXISTS T))
             (VALUES &OPTIONAL)))
(DEFUN-TYPE NUMERATOR (FUN (RATIONAL) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE / (FUN (NUMBER &REST NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE WRITE-SEQUENCE
            (FUN
             (SEQUENCE STREAM &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE LISTEN
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE GET-SETF-EXPANSION (FUN (T &OPTIONAL (OR NULL LEXENV)) *))
(DEFUN-TYPE MULTIPLE-VALUE-BIND (FUN * NIL))
(DEFUN-TYPE INTEGER-DECODE-FLOAT
            (FUN (FLOAT)
                 (VALUES INTEGER (INTEGER -1127 971)
                         (OR (INTEGER -1 -1) (INTEGER 1 1)) &OPTIONAL)))
(DEFUN-TYPE MACROEXPAND
            (FUN (T &OPTIONAL (OR LEXENV NULL))
                 (VALUES T &OPTIONAL (MEMBER T NIL))))
(DEFUN-TYPE CONSTANTLY (FUN (T) (VALUES FUNCTION &OPTIONAL)))
(DEFUN-TYPE CDDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE ZEROP (FUN (NUMBER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SECOND (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE COPY-READTABLE
            (FUN (&OPTIONAL (OR READTABLE NULL) (OR READTABLE NULL))
                 (VALUES READTABLE &OPTIONAL)))
(DEFUN-TYPE TYPEP
            (FUN (T (OR CONS SYMBOL INSTANCE) &OPTIONAL (OR LEXENV NULL))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE BIT-NOT
            (FUN ((ARRAY BIT) &OPTIONAL (OR (ARRAY BIT) (MEMBER T NIL)))
                 (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE COPY-SEQ
            (FUN (SEQUENCE)
                 (VALUES
                  (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                  &OPTIONAL)))
(DEFUN-TYPE TRANSLATE-LOGICAL-PATHNAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY)
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE ENSURE-GENERIC-FUNCTION
            (FUN
             (T &REST T &KEY (ENVIRONMENT T) (DEFINITION-SOURCE T)
              &ALLOW-OTHER-KEYS)
             *))
(DEFUN-TYPE DEFSETF (FUN * NIL))
(DEFUN-TYPE COPY-LIST (FUN (LIST) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE REVAPPEND (FUN (LIST T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE STRING-LESSP
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE PPRINT-TABULAR
            (FUN
             ((OR STREAM (MEMBER NIL T)) T &OPTIONAL T T UNSIGNED-BYTE)
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE INVOKE-DEBUGGER (FUN (CONDITION) NIL))
(DEFUN-TYPE PROG (FUN * NIL))
(DEFUN-TYPE COMPILE-FILE-PATHNAME
            (FUN (T &KEY (OUTPUT-FILE T) &ALLOW-OTHER-KEYS)
                 (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE SHARED-INITIALIZE (FUN (T T &REST T &KEY &ALLOW-OTHER-KEYS) *))
(DEFUN-TYPE GETHASH
            (FUN (T HASH-TABLE &OPTIONAL T)
                 (VALUES T (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CDDAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE NAMESTRING
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING NULL)
              &OPTIONAL)))
(DEFUN-TYPE BIT-VECTOR-P (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SLOT-UNBOUND (FUN (T T T) *))
(DEFUN-TYPE FTRUNCATE
            (FUN (REAL &OPTIONAL REAL) (VALUES FLOAT REAL &OPTIONAL)))
(DEFUN-TYPE MACHINE-TYPE
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE ARITHMETIC-ERROR-OPERATION (FUN (T) *))
(DEFUN-TYPE PPRINT-TAB
            (FUN
             ((MEMBER LINE SECTION LINE-RELATIVE SECTION-RELATIVE)
              UNSIGNED-BYTE UNSIGNED-BYTE &OPTIONAL
              (OR STREAM (MEMBER NIL T)))
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE NOTEVERY
            (FUN ((OR FUNCTION SYMBOL) SEQUENCE &REST SEQUENCE)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CHARACTERP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ASSOC-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE CHARACTER (FUN (T) (VALUES CHARACTER &OPTIONAL)))
(DEFUN-TYPE FROUND
            (FUN (REAL &OPTIONAL REAL) (VALUES FLOAT REAL &OPTIONAL)))
(DEFUN-TYPE MAPCAR
            (FUN ((OR FUNCTION SYMBOL) LIST &REST LIST)
                 (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE FLOOR
            (FUN (REAL &OPTIONAL REAL) (VALUES INTEGER REAL &OPTIONAL)))
(DEFUN-TYPE COPY-SYMBOL
            (FUN (SYMBOL &OPTIONAL T) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE ALPHANUMERICP
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE METHOD-COMBINATION-ERROR
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING FUNCTION)
              &REST T)
             *))
(DEFUN-TYPE UNWIND-PROTECT (FUN * NIL))
(DEFUN-TYPE LOGAND (FUN (&REST INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE CADDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE DEFINE-METHOD-COMBINATION (FUN * NIL))
(DEFUN-TYPE DECLAIM (FUN * NIL))
(DEFUN-TYPE MAKE-PACKAGE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (USE LIST) (NICKNAMES LIST)
              (INTERNAL-SYMBOLS (MOD 4611686018427387901))
              (EXTERNAL-SYMBOLS (MOD 4611686018427387901)))
             (VALUES PACKAGE &OPTIONAL)))
(DEFUN-TYPE PUSHNEW (FUN * NIL))
(DEFUN-TYPE FUNCTION (FUN * NIL))
(DEFUN-TYPE PACKAGE-SHADOWING-SYMBOLS
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE RASSOC
            (FUN
             (T LIST &KEY (KEY (OR FUNCTION SYMBOL))
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE MAKE-LOAD-FORM-SAVING-SLOTS
            (FUN (T &KEY (SLOT-NAMES T) (ENVIRONMENT T))
                 (VALUES T T &OPTIONAL)))
(DEFUN-TYPE SETQ (FUN * NIL))
(DEFUN-TYPE HASH-TABLE-SIZE
            (FUN (HASH-TABLE)
                 (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE CONS (FUN (T T) (VALUES CONS &OPTIONAL)))
(DEFUN-TYPE SUBLIS
            (FUN
             (LIST T &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE TWO-WAY-STREAM-OUTPUT-STREAM
            (FUN (TWO-WAY-STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE WITH-STANDARD-IO-SYNTAX (FUN * NIL))
(DEFUN-TYPE CLRHASH (FUN (HASH-TABLE) (VALUES HASH-TABLE &OPTIONAL)))
(DEFUN-TYPE BOTH-CASE-P
            (FUN (CHARACTER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAKE-LOAD-FORM (FUN (T &OPTIONAL T) *))
(DEFUN-TYPE CHAR-LESSP
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE DIRECTORY
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (RESOLVE-SYMLINKS T))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE GET-DISPATCH-MACRO-CHARACTER
            (FUN (CHARACTER CHARACTER &OPTIONAL (OR READTABLE NULL))
                 (VALUES (OR FUNCTION SYMBOL) &OPTIONAL)))
(DEFUN-TYPE MASK-FIELD (FUN (CONS INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE MAX (FUN (REAL &REST REAL) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE CHAR-CODE (FUN (CHARACTER) (VALUES (MOD 1114112) &OPTIONAL)))
(DEFUN-TYPE PROBE-FILE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES (OR PATHNAME NULL) &OPTIONAL)))
(DEFUN-TYPE METHOD-QUALIFIERS (FUN (&REST T) T))
(DEFUN-TYPE LOGICAL-PATHNAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES LOGICAL-PATHNAME &OPTIONAL)))
(DEFUN-TYPE NINTERSECTION
            (FUN
             (LIST LIST &KEY (KEY (OR FUNCTION SYMBOL))
                   (TEST (OR FUNCTION SYMBOL))
                   (TEST-NOT (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE PATHNAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM))
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE GCD (FUN (&REST INTEGER) (VALUES UNSIGNED-BYTE &OPTIONAL)))
(DEFUN-TYPE DEFINE-MODIFY-MACRO (FUN * NIL))
(DEFUN-TYPE CAAADR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CHAR-GREATERP
            (FUN (CHARACTER &REST CHARACTER)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE MAKE-PATHNAME
            (FUN
             (&KEY
              (DEFAULTS
               (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                   FILE-STREAM))
              (HOST
               (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING HOST NULL))
              (DEVICE
               (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                   (MEMBER NIL UNSPECIFIC UNC)))
              (DIRECTORY
               (OR CONS (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                   (MEMBER WILD NIL)))
              (NAME
               (OR PATTERN (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                   (MEMBER NIL UNSPECIFIC WILD)))
              (TYPE
               (OR PATTERN (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                   (MEMBER NIL UNSPECIFIC WILD)))
              (VERSION (OR INTEGER (MEMBER NIL NEWEST WILD UNSPECIFIC)))
              (CASE (MEMBER LOCAL COMMON)))
             (VALUES PATHNAME &OPTIONAL)))
(DEFUN-TYPE PATHNAME-DEVICE
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (CASE (MEMBER LOCAL COMMON)))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING (MEMBER NIL UNSPECIFIC UNC))
              &OPTIONAL)))
(DEFUN-TYPE STRING/=
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE SHORT-SITE-NAME
            (FUN NIL
                 (VALUES
                  (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                      SIMPLE-BASE-STRING NULL)
                  &OPTIONAL)))
(DEFUN-TYPE CONCATENATE
            (FUN ((OR CONS SYMBOL INSTANCE) &REST SEQUENCE)
                 (VALUES
                  (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                  &OPTIONAL)))
(DEFUN-TYPE <= (FUN (REAL &REST REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE CONSP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE FIND-SYMBOL
            (FUN
             (STRING &OPTIONAL
                     (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING
                         SYMBOL CHARACTER PACKAGE))
             (VALUES SYMBOL (MEMBER INTERNAL EXTERNAL INHERITED NIL)
                     &OPTIONAL)))
(DEFUN-TYPE FIFTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE MAKE-ECHO-STREAM
            (FUN (STREAM STREAM) (VALUES STREAM &OPTIONAL)))
(DEFUN-TYPE DISASSEMBLE
            (FUN
             ((OR FUNCTION SYMBOL CONS) &KEY (STREAM STREAM)
              (USE-LABELS T))
             (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PPRINT (FUN (T &OPTIONAL T) (VALUES &OPTIONAL)))
(DEFUN-TYPE EVAL (FUN (T) *))
(DEFUN-TYPE NBUTLAST
            (FUN (LIST &OPTIONAL UNSIGNED-BYTE) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE PSETF (FUN * NIL))
(DEFUN-TYPE IN-PACKAGE (FUN * NIL))
(DEFUN-TYPE DIGIT-CHAR
            (FUN (UNSIGNED-BYTE &OPTIONAL (INTEGER 2 36))
                 (VALUES (OR CHARACTER NULL) &OPTIONAL)))
(DEFUN-TYPE ARRAY-DIMENSION
            (FUN (ARRAY (MOD 65529))
                 (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE FIRST (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE STRING-EQUAL
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE IDENTITY (FUN (T) (VALUES T &OPTIONAL)))
(DEFUN-TYPE COPY-ALIST (FUN (LIST) (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE FILE-LENGTH
            (FUN (STREAM) (VALUES (OR UNSIGNED-BYTE NULL) &OPTIONAL)))
(DEFUN-TYPE FUNCTIONP (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE NSUBSTITUTE-IF-NOT
            (FUN
             (T (OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE NSUBST-IF-NOT
            (FUN
             (T (OR FUNCTION SYMBOL) T &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES T &OPTIONAL)))
(DEFUN-TYPE BYTE
            (FUN ((UNSIGNED-BYTE 62) (UNSIGNED-BYTE 62))
                 (VALUES CONS &OPTIONAL)))
(DEFUN-TYPE LOAD-LOGICAL-PATHNAME-TRANSLATIONS
            (FUN (STRING) (VALUES T &OPTIONAL)))
(DEFUN-TYPE COUNT-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (KEY (OR FUNCTION SYMBOL)))
             (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE REM (FUN (REAL REAL) (VALUES REAL &OPTIONAL)))
(DEFUN-TYPE READ-SEQUENCE
            (FUN
             (SEQUENCE STREAM &KEY (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901))))
             (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE INTERACTIVE-STREAM-P (FUN (T) *))
(DEFUN-TYPE LOGORC2 (FUN (INTEGER INTEGER) (VALUES INTEGER &OPTIONAL)))
(DEFUN-TYPE DEFPARAMETER (FUN * NIL))
(DEFUN-TYPE SYMBOL-PACKAGE
            (FUN (SYMBOL) (VALUES (OR PACKAGE NULL) &OPTIONAL)))
(DEFUN-TYPE INVALID-METHOD-ERROR
            (FUN
             (T (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING FUNCTION)
              &REST T)
             *))
(DEFUN-TYPE WITH-SIMPLE-RESTART (FUN * NIL))
(DEFUN-TYPE LOCALLY (FUN * NIL))
(DEFUN-TYPE DELETE-IF
            (FUN
             ((OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE STREAM-ELEMENT-TYPE (FUN (T) *))
(DEFUN-TYPE WITH-CONDITION-RESTARTS (FUN * NIL))
(DEFUN-TYPE FIND-ALL-SYMBOLS
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE FLOAT-SIGN
            (FUN (FLOAT &OPTIONAL FLOAT) (VALUES FLOAT &OPTIONAL)))
(DEFUN-TYPE LOGTEST
            (FUN (INTEGER INTEGER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ARRAY-ROW-MAJOR-INDEX
            (FUN (ARRAY &REST (MOD 4611686018427387901))
                 (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE PLUSP (FUN (REAL) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE Y-OR-N-P
            (FUN (&OPTIONAL STRING &REST T)
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE RESTART-NAME (FUN (RESTART) (VALUES SYMBOL &OPTIONAL)))
(DEFUN-TYPE CONSTANTP
            (FUN (T &OPTIONAL (OR LEXENV NULL))
                 (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE COSH
            (FUN (NUMBER)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE DELETE
            (FUN
             (T SEQUENCE &REST T &KEY (FROM-END T)
              (TEST (OR FUNCTION SYMBOL)) (TEST-NOT (OR FUNCTION SYMBOL))
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES SEQUENCE &OPTIONAL)))
(DEFUN-TYPE DEFMETHOD (FUN * NIL))
(DEFUN-TYPE FCEILING
            (FUN (REAL &OPTIONAL REAL) (VALUES FLOAT REAL &OPTIONAL)))
(DEFUN-TYPE INPUT-STREAM-P (FUN (T) *))
(DEFUN-TYPE SIMPLE-STRING-P (FUN (T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE ROW-MAJOR-AREF
            (FUN (ARRAY (MOD 4611686018427387901)) (VALUES T &OPTIONAL)))
(DEFUN-TYPE FFLOOR
            (FUN (REAL &OPTIONAL REAL) (VALUES FLOAT REAL &OPTIONAL)))
(DEFUN-TYPE HASH-TABLE-REHASH-SIZE
            (FUN (HASH-TABLE)
                 (VALUES
                  (OR (MOD 4611686018427387901) (SINGLE-FLOAT (1.0)))
                  &OPTIONAL)))
(DEFUN-TYPE NTH-VALUE (FUN * NIL))
(DEFUN-TYPE CDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE INCF (FUN * NIL))
(DEFUN-TYPE INSPECT (FUN (T) (VALUES &OPTIONAL)))
(DEFUN-TYPE DEFCONSTANT (FUN * NIL))
(DEFUN-TYPE VECTOR-PUSH
            (FUN (T (AND VECTOR (NOT SIMPLE-ARRAY)))
                 (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE STORE-VALUE
            (FUN (T &OPTIONAL (OR CONDITION NULL))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE INVOKE-RESTART
            (FUN ((OR (AND SYMBOL (NOT NULL)) RESTART) &REST T) *))
(DEFUN-TYPE DEFINE-SYMBOL-MACRO (FUN * NIL))
(DEFUN-TYPE PUSH (FUN * NIL))
(DEFUN-TYPE DEFINE-CONDITION (FUN * NIL))
(DEFUN-TYPE PROG* (FUN * NIL))
(DEFUN-TYPE RETURN (FUN * NIL))
(DEFUN-TYPE SIGNUM (FUN (NUMBER) (VALUES NUMBER &OPTIONAL)))
(DEFUN-TYPE UNREAD-CHAR
            (FUN (CHARACTER &OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE CADAR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CDDDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE ATAN
            (FUN (NUMBER &OPTIONAL REAL)
                 (VALUES
                  (OR SINGLE-FLOAT DOUBLE-FLOAT (COMPLEX SINGLE-FLOAT)
                      (COMPLEX DOUBLE-FLOAT))
                  &OPTIONAL)))
(DEFUN-TYPE PATHNAME-NAME
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME
                  FILE-STREAM)
              &KEY (CASE (MEMBER LOCAL COMMON)))
             (VALUES
              (OR (SIMPLE-ARRAY CHARACTER (*)) (SIMPLE-ARRAY NIL (*))
                  SIMPLE-BASE-STRING PATTERN (MEMBER NIL UNSPECIFIC WILD))
              &OPTIONAL)))
(DEFUN-TYPE SLOT-EXISTS-P (FUN (T T) (VALUES (MEMBER NIL T) &OPTIONAL)))
(DEFUN-TYPE RASSOC-IF-NOT
            (FUN
             ((OR FUNCTION SYMBOL) LIST &KEY (KEY (OR FUNCTION SYMBOL)))
             (VALUES LIST &OPTIONAL)))
(DEFUN-TYPE WRITE-LINE
            (FUN
             (STRING &OPTIONAL (OR STREAM (MEMBER NIL T)) &KEY
                     (START (MOD 4611686018427387901))
                     (END (OR NULL (MOD 4611686018427387901))))
             (VALUES STRING &OPTIONAL)))
(DEFUN-TYPE STRING<
            (FUN
             ((OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER)
              &KEY (START1 (MOD 4611686018427387901))
              (END1 (OR NULL (MOD 4611686018427387901)))
              (START2 (MOD 4611686018427387901))
              (END2 (OR NULL (MOD 4611686018427387901))))
             (VALUES (OR (MOD 4611686018427387901) NULL) &OPTIONAL)))
(DEFUN-TYPE MAP
            (FUN
             ((OR CONS SYMBOL INSTANCE) (OR FUNCTION SYMBOL) SEQUENCE
              &REST SEQUENCE)
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE BIT-ORC2
            (FUN
             ((ARRAY BIT) (ARRAY BIT) &OPTIONAL
              (OR (ARRAY BIT) (MEMBER T NIL)))
             (VALUES (ARRAY BIT) &OPTIONAL)))
(DEFUN-TYPE MULTIPLE-VALUE-CALL (FUN * NIL))
(DEFUN-TYPE CDDDDR (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE QUOTE (FUN * NIL))
(DEFUN-TYPE NINTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE CEILING
            (FUN (REAL &OPTIONAL REAL) (VALUES INTEGER REAL &OPTIONAL)))
(DEFUN-TYPE /=
            (FUN (NUMBER &REST NUMBER) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE FOURTH (FUN (LIST) (VALUES T &OPTIONAL)))
(DEFUN-TYPE READ
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)) T T T)
                 (VALUES T &OPTIONAL)))
(DEFUN-TYPE DEFVAR (FUN * NIL))
(DEFUN-TYPE VECTOR-PUSH-EXTEND
            (FUN
             (T (AND VECTOR (NOT SIMPLE-ARRAY)) &OPTIONAL
              (INTEGER 1 4611686018427387900))
             (VALUES (MOD 4611686018427387901) &OPTIONAL)))
(DEFUN-TYPE UNUSE-PACKAGE
            (FUN
             ((OR CONS (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE)
              &OPTIONAL
              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING SYMBOL
                  CHARACTER PACKAGE))
             (VALUES (MEMBER T) &OPTIONAL)))
(DEFUN-TYPE EQUAL (FUN (T T) (VALUES (MEMBER T NIL) &OPTIONAL)))
(DEFUN-TYPE SUBSTITUTE-IF
            (FUN
             (T (OR FUNCTION SYMBOL) SEQUENCE &REST T &KEY (FROM-END T)
              (START (MOD 4611686018427387901))
              (END (OR NULL (MOD 4611686018427387901)))
              (COUNT (OR NULL INTEGER)) (KEY (OR FUNCTION SYMBOL)))
             (VALUES (OR (SIMPLE-ARRAY * (*)) CONS NULL EXTENDED-SEQUENCE)
                     &OPTIONAL)))
(DEFUN-TYPE CLEAR-OUTPUT
            (FUN (&OPTIONAL (OR STREAM (MEMBER NIL T)))
                 (VALUES NULL &OPTIONAL)))
(DEFUN-TYPE PROG2 (FUN * NIL))
