(in-package :pluggable-types/decl)

(declaim
 (ftype* (all (a) (function (a) a))
         identity)
 (ftype* (or
          (all (a b) (function ((function (a) b) (list-of a)) (list-of b)))
          (function ((function t t) list) list))
         mapcar)
 (ftype* (all (a) (function (unsigned-byte (list-of a)) a))
         nth)
 (ftype* (all (a) (function ((list-of a)) a))
         first)
 (ftype* (all (a) (function ((list-of a)) (list-of a)))
         rest)
 (ftype*
  (or (all (a b) (function ((cons-of a b)) a))
      (all (a) (function ((list-of a)) a)))
  car)
 (ftype* (or
          (all (a b) (function ((cons-of a b)) b))
          (all (a) (function ((list-of a)) (list-of a))))
         cdr)
 (ftype* (all (a b) (function (a b) (cons-of a b)))
         cons)
 (ftype* (let ((test-function (elem-type)
                              (function (elem-type elem-type) boolean)))
           (all (a b)
                (function (a (cons-of a b)
                             &key (:test (test-function (cons-of a b)))
                             (:test-not (test-function (cons-of a b)))
                             (:key (function ((cons-of a b)) t)))
                          (or b null)))
           (all (a b)
                (function (a (alist-of a b)
                             &key (:test (test-function (alist-of a b)))
                             (:test-not (test-function (alist-of a b)))
                             (:key (function ((alist-of a b) t))))
                          (or b null)))
           (function
            (t list &key (:test (or function symbol))
               (:test-not (or function symbol))
               (:key (or function symbol)))))
         assoc))
